### ISSUE TITLE
Issues starting minikube in bitbucket pipeline

### ISSUE THREAD

**Issue by PhilipDeegan** [minikube-ci/examples#11]
Hi, I posted an issue [here](https://github.com/kubernetes/minikube/issues/16786) a while back and I've seen no interaction.

If anyone has any ideas how to change the mount directory to one allowed by bitbucket please let me know and I will test it.

**Comment by rlgomes** [comment]
A simple solution would be if we could override the default behavior that creates this volume request `-v minikube:/var` with a simple environment variable being set such as `MINIKUBE_VOLUME_PATH=something/else/` in the case of the bitbucket situation which is my issue as well I'd set it ot the other variable like so `MINIKUBE_VOLUME_PATH=${BITBUCKET_CLONE_DIR}` and things owuld just work.

**Comment by mkonecny-atlassian** [comment]
@PhilipDeegan you've closed this issue but I don't see a way to configure this, as I am trying to run `minikube` in Bitbucket Pipelines. Did you use your own fork?

**Comment by PhilipDeegan** [comment]
sorry, I don't work with kubernetes anymore
@mkonecny-atlassian
